"""initial_schema

Revision ID: 9fdbd155f1dd
Revises:
Create Date: 2026-07-26 19:07:39.432884

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fdbd155f1dd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "census_county",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fips_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("census_year", sa.SmallInteger(), nullable=False),
        sa.Column("total_pop", sa.Integer(), nullable=True),
        sa.Column("median_income", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pct_under_18", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pct_over_65", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pct_nonwhite", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "cancer_mortality_female_per_100k", sa.Numeric(precision=6, scale=1), nullable=True
        ),
        sa.Column(
            "cancer_mortality_male_per_100k", sa.Numeric(precision=6, scale=1), nullable=True
        ),
        sa.Column(
            "heart_disease_mortality_per_100k", sa.Numeric(precision=6, scale=1), nullable=True
        ),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                spatial_index=False,
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fips_code"),
    )
    op.create_index(
        "idx_county_boundary", "census_county", ["boundary"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "chemicals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cas_number", sa.String(length=12), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("atsdr_url", sa.Text(), nullable=True),
        sa.Column("pubchem_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chemicals_cas_number",
        "chemicals",
        ["cas_number"],
        unique=True,
        postgresql_where="cas_number IS NOT NULL",
    )
    op.create_table(
        "facilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tri_facility_id", sa.String(length=15), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("county", sa.Text(), nullable=True),
        sa.Column("naics_code", sa.String(length=6), nullable=True),
        sa.Column("naics_desc", sa.Text(), nullable=True),
        sa.Column("frs_id", sa.String(length=12), nullable=True),
        sa.Column("primary_sic", sa.String(length=4), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tri_facility_id"),
    )
    op.create_index(
        "idx_facilities_location", "facilities", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index("idx_facilities_state", "facilities", ["state_code"], unique=False)
    op.create_table(
        "npri_facilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("npri_id", sa.String(length=12), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("province", sa.String(length=2), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("npri_id"),
    )
    op.create_index(
        "idx_npri_facilities_location",
        "npri_facilities",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "nuclear_plants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_name", sa.Text(), nullable=False),
        sa.Column("operator", sa.Text(), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_nuclear_plants_location",
        "nuclear_plants",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "superfund_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epa_id", sa.String(length=12), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("county", sa.Text(), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("hrs_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("npl_date", sa.Date(), nullable=True),
        sa.Column("epa_progress_url", sa.Text(), nullable=True),
        sa.Column("contaminants", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epa_id"),
    )
    op.create_index(
        "idx_superfund_location",
        "superfund_sites",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("idx_superfund_state", "superfund_sites", ["state_code"], unique=False)
    op.create_table(
        "release_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.Column("chemical_id", sa.Integer(), nullable=False),
        sa.Column("reporting_year", sa.SmallInteger(), nullable=False),
        sa.Column("total_release_lbs", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("air_release_lbs", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("water_release_lbs", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("land_release_lbs", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("underground_release_lbs", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("off_site_lbs", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("unit_of_measure", sa.String(length=6), nullable=False),
        sa.Column("form_type", sa.String(length=1), nullable=False),
        sa.ForeignKeyConstraint(
            ["chemical_id"],
            ["chemicals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_releases_chemical", "release_events", ["chemical_id"], unique=False)
    op.create_index("idx_releases_facility", "release_events", ["facility_id"], unique=False)
    op.create_index("idx_releases_year", "release_events", ["reporting_year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop application tables in reverse dependency order
    op.drop_index("idx_releases_year", table_name="release_events")
    op.drop_index("idx_releases_facility", table_name="release_events")
    op.drop_index("idx_releases_chemical", table_name="release_events")
    op.drop_table("release_events")
    op.drop_index("idx_superfund_state", table_name="superfund_sites")
    op.drop_index("idx_superfund_location", table_name="superfund_sites", postgresql_using="gist")
    op.drop_table("superfund_sites")
    op.drop_index(
        "idx_nuclear_plants_location", table_name="nuclear_plants", postgresql_using="gist"
    )
    op.drop_table("nuclear_plants")
    op.drop_index(
        "idx_npri_facilities_location", table_name="npri_facilities", postgresql_using="gist"
    )
    op.drop_table("npri_facilities")
    op.drop_index("idx_county_boundary", table_name="census_county", postgresql_using="gist")
    op.drop_table("census_county")
    op.drop_index("idx_facilities_state", table_name="facilities")
    op.drop_index("idx_facilities_location", table_name="facilities", postgresql_using="gist")
    op.drop_table("facilities")
    op.drop_index(
        "idx_chemicals_cas_number",
        table_name="chemicals",
        postgresql_where="cas_number IS NOT NULL",
    )
    op.drop_table("chemicals")
